version: '3.8'

networks:
  chat-net:
    driver: overlay
    attachable: true

services:
  rethinkdb-master:
    image: rethinkdb
    ports:
      - "28015:28015"
      - "8080:8080"
    networks:
      - chat-net
    volumes:
      - rethinkdb-master-data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  rethinkdb-replica:
    image: rethinkdb
    command: rethinkdb --bind all --join rethinkdb-master:29015
    networks:
      - chat-net
    volumes:
      - rethinkdb-replica-data:/data
    deploy:
      replicas: 1 # Aumentado a 2 para tener un total de 3 nodos de DB
      restart_policy:
        condition: on-failure
    depends_on:
      - rethinkdb-master

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    networks:
      - chat-net
    deploy:
      replicas: 1 # Se mantiene en 1. Ver nota sobre alta disponibilidad.
      restart_policy:
        condition: on-failure

  api:
    image: chat-api:latest
    environment:
      RDB_HOST: rethinkdb-master
      RDB_PORT: 28015
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_PUBLIC_URL: http://minio:9000
      JWT_SECRET: super_secreto
    depends_on:
      - rethinkdb-master
      - rethinkdb-replica
      - minio
    networks:
      - chat-net
    deploy:
      replicas: 1 # Aumentado a 3 para alta disponibilidad
      restart_policy:
        condition: on-failure

  proxy:
    image: caddy:latest
    ports:
      - "80:80"
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - chat-net
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  minio-data:
  rethinkdb-master-data:
  rethinkdb-replica-data:
