version: '3.8'

networks:
  chat-net:
    driver: overlay
    attachable: true

services:
  rethinkdb-master:
    image: rethinkdb
    command: rethinkdb --bind all
    ports:
      - "28015:28015"
      - "8080:8080"
    networks:
      - chat-net
    volumes:
      - rethinkdb-master-data:/data
    healthcheck:
      test: ["CMD", "rethinkdb", "ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  rethinkdb-replica:
    image: rethinkdb
    command: rethinkdb --bind all --join rethinkdb-master:29015
    networks:
      - chat-net
    volumes:
      - rethinkdb-replica-data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    networks:
      - chat-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  api:
    build: ./api
    image: chat-api:latest
    environment:
      RDB_HOST: rethinkdb-master
      RDB_PORT: 28015
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_PUBLIC_URL: http://192.168.122.101:9000
      JWT_SECRET: super_secreto
    networks:
      - chat-net
    depends_on:
      - rethinkdb-master
      - minio
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  web:
    build: ./web
    image: chat-web:latest
    networks:
      - chat-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  proxy:
    image: caddy:latest
    ports:
      - "80:80"
      - "9000:9000"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - chat-net
    depends_on:
      - api
      - minio
      - web
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

volumes:
  minio-data:
  rethinkdb-master-data:
  rethinkdb-replica-data:
